/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/~__root'
import { Route as CompareRouteImport } from './pages/~compare'
import { Route as IndexRouteImport } from './pages/~index'
import { Route as VladniBudgetNameRouteImport } from './pages/~vladni/~$budgetName'
import { Route as VladniIndexRouteImport } from './pages/~vladni/~index'
import { Route as PublishedIndexRouteImport } from './pages/~published/~index'
import { Route as PodporitIndexRouteImport } from './pages/~podporit/~index'
import { Route as MyIndexRouteImport } from './pages/~my/~index'
import { Route as CompareIndexRouteImport } from './pages/~compare/~index'
import { Route as AgregatedIndexRouteImport } from './pages/~agregated/~index'
import { Route as CompareBudgetNameSecondBudgetNameRouteImport } from './pages/~compare/~$budgetName/~$secondBudgetName'
import { Route as VladniBudgetNameIndexRouteImport } from './pages/~vladni/~$budgetName/~index'
import { Route as CompareBudgetNameIndexRouteImport } from './pages/~compare/~$budgetName/~index'
import { Route as VladniBudgetNameVydajeSplatRouteImport } from './pages/~vladni/~$budgetName/~vydaje.$'
import { Route as VladniBudgetNamePrijmySplatRouteImport } from './pages/~vladni/~$budgetName/~prijmy.$'
import { Route as CompareBudgetNameSecondBudgetNameIndexRouteImport } from './pages/~compare/~$budgetName/~$secondBudgetName/~index'
import { Route as CompareBudgetNameSecondBudgetNameVydajeSplatRouteImport } from './pages/~compare/~$budgetName/~$secondBudgetName/~vydaje.$'
import { Route as CompareBudgetNameSecondBudgetNamePrijmySplatRouteImport } from './pages/~compare/~$budgetName/~$secondBudgetName/~prijmy.$'

const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VladniBudgetNameRoute = VladniBudgetNameRouteImport.update({
  id: '/vladni/$budgetName',
  path: '/vladni/$budgetName',
  getParentRoute: () => rootRouteImport,
} as any)
const VladniIndexRoute = VladniIndexRouteImport.update({
  id: '/vladni/',
  path: '/vladni/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishedIndexRoute = PublishedIndexRouteImport.update({
  id: '/published/',
  path: '/published/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodporitIndexRoute = PodporitIndexRouteImport.update({
  id: '/podporit/',
  path: '/podporit/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyIndexRoute = MyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompareRoute,
} as any)
const AgregatedIndexRoute = AgregatedIndexRouteImport.update({
  id: '/agregated/',
  path: '/agregated/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareBudgetNameSecondBudgetNameRoute =
  CompareBudgetNameSecondBudgetNameRouteImport.update({
    id: '/$budgetName/$secondBudgetName',
    path: '/$budgetName/$secondBudgetName',
    getParentRoute: () => CompareRoute,
  } as any)
const VladniBudgetNameIndexRoute = VladniBudgetNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VladniBudgetNameRoute,
} as any)
const CompareBudgetNameIndexRoute = CompareBudgetNameIndexRouteImport.update({
  id: '/$budgetName/',
  path: '/$budgetName/',
  getParentRoute: () => CompareRoute,
} as any)
const VladniBudgetNameVydajeSplatRoute =
  VladniBudgetNameVydajeSplatRouteImport.update({
    id: '/vydaje/$',
    path: '/vydaje/$',
    getParentRoute: () => VladniBudgetNameRoute,
  } as any)
const VladniBudgetNamePrijmySplatRoute =
  VladniBudgetNamePrijmySplatRouteImport.update({
    id: '/prijmy/$',
    path: '/prijmy/$',
    getParentRoute: () => VladniBudgetNameRoute,
  } as any)
const CompareBudgetNameSecondBudgetNameIndexRoute =
  CompareBudgetNameSecondBudgetNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompareBudgetNameSecondBudgetNameRoute,
  } as any)
const CompareBudgetNameSecondBudgetNameVydajeSplatRoute =
  CompareBudgetNameSecondBudgetNameVydajeSplatRouteImport.update({
    id: '/vydaje/$',
    path: '/vydaje/$',
    getParentRoute: () => CompareBudgetNameSecondBudgetNameRoute,
  } as any)
const CompareBudgetNameSecondBudgetNamePrijmySplatRoute =
  CompareBudgetNameSecondBudgetNamePrijmySplatRouteImport.update({
    id: '/prijmy/$',
    path: '/prijmy/$',
    getParentRoute: () => CompareBudgetNameSecondBudgetNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRouteWithChildren
  '/agregated': typeof AgregatedIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/my': typeof MyIndexRoute
  '/podporit': typeof PodporitIndexRoute
  '/published': typeof PublishedIndexRoute
  '/vladni': typeof VladniIndexRoute
  '/vladni/$budgetName': typeof VladniBudgetNameRouteWithChildren
  '/compare/$budgetName': typeof CompareBudgetNameIndexRoute
  '/vladni/$budgetName/': typeof VladniBudgetNameIndexRoute
  '/compare/$budgetName/$secondBudgetName': typeof CompareBudgetNameSecondBudgetNameRouteWithChildren
  '/compare/$budgetName/$secondBudgetName/': typeof CompareBudgetNameSecondBudgetNameIndexRoute
  '/vladni/$budgetName/prijmy/$': typeof VladniBudgetNamePrijmySplatRoute
  '/vladni/$budgetName/vydaje/$': typeof VladniBudgetNameVydajeSplatRoute
  '/compare/$budgetName/$secondBudgetName/prijmy/$': typeof CompareBudgetNameSecondBudgetNamePrijmySplatRoute
  '/compare/$budgetName/$secondBudgetName/vydaje/$': typeof CompareBudgetNameSecondBudgetNameVydajeSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agregated': typeof AgregatedIndexRoute
  '/compare': typeof CompareIndexRoute
  '/my': typeof MyIndexRoute
  '/podporit': typeof PodporitIndexRoute
  '/published': typeof PublishedIndexRoute
  '/vladni': typeof VladniIndexRoute
  '/compare/$budgetName': typeof CompareBudgetNameIndexRoute
  '/vladni/$budgetName': typeof VladniBudgetNameIndexRoute
  '/compare/$budgetName/$secondBudgetName': typeof CompareBudgetNameSecondBudgetNameIndexRoute
  '/vladni/$budgetName/prijmy/$': typeof VladniBudgetNamePrijmySplatRoute
  '/vladni/$budgetName/vydaje/$': typeof VladniBudgetNameVydajeSplatRoute
  '/compare/$budgetName/$secondBudgetName/prijmy/$': typeof CompareBudgetNameSecondBudgetNamePrijmySplatRoute
  '/compare/$budgetName/$secondBudgetName/vydaje/$': typeof CompareBudgetNameSecondBudgetNameVydajeSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRouteWithChildren
  '/agregated/': typeof AgregatedIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/my/': typeof MyIndexRoute
  '/podporit/': typeof PodporitIndexRoute
  '/published/': typeof PublishedIndexRoute
  '/vladni/': typeof VladniIndexRoute
  '/vladni/$budgetName': typeof VladniBudgetNameRouteWithChildren
  '/compare/$budgetName/': typeof CompareBudgetNameIndexRoute
  '/vladni/$budgetName/': typeof VladniBudgetNameIndexRoute
  '/compare/$budgetName/$secondBudgetName': typeof CompareBudgetNameSecondBudgetNameRouteWithChildren
  '/compare/$budgetName/$secondBudgetName/': typeof CompareBudgetNameSecondBudgetNameIndexRoute
  '/vladni/$budgetName/prijmy/$': typeof VladniBudgetNamePrijmySplatRoute
  '/vladni/$budgetName/vydaje/$': typeof VladniBudgetNameVydajeSplatRoute
  '/compare/$budgetName/$secondBudgetName/prijmy/$': typeof CompareBudgetNameSecondBudgetNamePrijmySplatRoute
  '/compare/$budgetName/$secondBudgetName/vydaje/$': typeof CompareBudgetNameSecondBudgetNameVydajeSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/agregated'
    | '/compare/'
    | '/my'
    | '/podporit'
    | '/published'
    | '/vladni'
    | '/vladni/$budgetName'
    | '/compare/$budgetName'
    | '/vladni/$budgetName/'
    | '/compare/$budgetName/$secondBudgetName'
    | '/compare/$budgetName/$secondBudgetName/'
    | '/vladni/$budgetName/prijmy/$'
    | '/vladni/$budgetName/vydaje/$'
    | '/compare/$budgetName/$secondBudgetName/prijmy/$'
    | '/compare/$budgetName/$secondBudgetName/vydaje/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agregated'
    | '/compare'
    | '/my'
    | '/podporit'
    | '/published'
    | '/vladni'
    | '/compare/$budgetName'
    | '/vladni/$budgetName'
    | '/compare/$budgetName/$secondBudgetName'
    | '/vladni/$budgetName/prijmy/$'
    | '/vladni/$budgetName/vydaje/$'
    | '/compare/$budgetName/$secondBudgetName/prijmy/$'
    | '/compare/$budgetName/$secondBudgetName/vydaje/$'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/agregated/'
    | '/compare/'
    | '/my/'
    | '/podporit/'
    | '/published/'
    | '/vladni/'
    | '/vladni/$budgetName'
    | '/compare/$budgetName/'
    | '/vladni/$budgetName/'
    | '/compare/$budgetName/$secondBudgetName'
    | '/compare/$budgetName/$secondBudgetName/'
    | '/vladni/$budgetName/prijmy/$'
    | '/vladni/$budgetName/vydaje/$'
    | '/compare/$budgetName/$secondBudgetName/prijmy/$'
    | '/compare/$budgetName/$secondBudgetName/vydaje/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRouteWithChildren
  AgregatedIndexRoute: typeof AgregatedIndexRoute
  MyIndexRoute: typeof MyIndexRoute
  PodporitIndexRoute: typeof PodporitIndexRoute
  PublishedIndexRoute: typeof PublishedIndexRoute
  VladniIndexRoute: typeof VladniIndexRoute
  VladniBudgetNameRoute: typeof VladniBudgetNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vladni/$budgetName': {
      id: '/vladni/$budgetName'
      path: '/vladni/$budgetName'
      fullPath: '/vladni/$budgetName'
      preLoaderRoute: typeof VladniBudgetNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vladni/': {
      id: '/vladni/'
      path: '/vladni'
      fullPath: '/vladni'
      preLoaderRoute: typeof VladniIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/published/': {
      id: '/published/'
      path: '/published'
      fullPath: '/published'
      preLoaderRoute: typeof PublishedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podporit/': {
      id: '/podporit/'
      path: '/podporit'
      fullPath: '/podporit'
      preLoaderRoute: typeof PodporitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/': {
      id: '/my/'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof CompareRoute
    }
    '/agregated/': {
      id: '/agregated/'
      path: '/agregated'
      fullPath: '/agregated'
      preLoaderRoute: typeof AgregatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$budgetName/$secondBudgetName': {
      id: '/compare/$budgetName/$secondBudgetName'
      path: '/$budgetName/$secondBudgetName'
      fullPath: '/compare/$budgetName/$secondBudgetName'
      preLoaderRoute: typeof CompareBudgetNameSecondBudgetNameRouteImport
      parentRoute: typeof CompareRoute
    }
    '/vladni/$budgetName/': {
      id: '/vladni/$budgetName/'
      path: '/'
      fullPath: '/vladni/$budgetName/'
      preLoaderRoute: typeof VladniBudgetNameIndexRouteImport
      parentRoute: typeof VladniBudgetNameRoute
    }
    '/compare/$budgetName/': {
      id: '/compare/$budgetName/'
      path: '/$budgetName'
      fullPath: '/compare/$budgetName'
      preLoaderRoute: typeof CompareBudgetNameIndexRouteImport
      parentRoute: typeof CompareRoute
    }
    '/vladni/$budgetName/vydaje/$': {
      id: '/vladni/$budgetName/vydaje/$'
      path: '/vydaje/$'
      fullPath: '/vladni/$budgetName/vydaje/$'
      preLoaderRoute: typeof VladniBudgetNameVydajeSplatRouteImport
      parentRoute: typeof VladniBudgetNameRoute
    }
    '/vladni/$budgetName/prijmy/$': {
      id: '/vladni/$budgetName/prijmy/$'
      path: '/prijmy/$'
      fullPath: '/vladni/$budgetName/prijmy/$'
      preLoaderRoute: typeof VladniBudgetNamePrijmySplatRouteImport
      parentRoute: typeof VladniBudgetNameRoute
    }
    '/compare/$budgetName/$secondBudgetName/': {
      id: '/compare/$budgetName/$secondBudgetName/'
      path: '/'
      fullPath: '/compare/$budgetName/$secondBudgetName/'
      preLoaderRoute: typeof CompareBudgetNameSecondBudgetNameIndexRouteImport
      parentRoute: typeof CompareBudgetNameSecondBudgetNameRoute
    }
    '/compare/$budgetName/$secondBudgetName/vydaje/$': {
      id: '/compare/$budgetName/$secondBudgetName/vydaje/$'
      path: '/vydaje/$'
      fullPath: '/compare/$budgetName/$secondBudgetName/vydaje/$'
      preLoaderRoute: typeof CompareBudgetNameSecondBudgetNameVydajeSplatRouteImport
      parentRoute: typeof CompareBudgetNameSecondBudgetNameRoute
    }
    '/compare/$budgetName/$secondBudgetName/prijmy/$': {
      id: '/compare/$budgetName/$secondBudgetName/prijmy/$'
      path: '/prijmy/$'
      fullPath: '/compare/$budgetName/$secondBudgetName/prijmy/$'
      preLoaderRoute: typeof CompareBudgetNameSecondBudgetNamePrijmySplatRouteImport
      parentRoute: typeof CompareBudgetNameSecondBudgetNameRoute
    }
  }
}

interface CompareBudgetNameSecondBudgetNameRouteChildren {
  CompareBudgetNameSecondBudgetNameIndexRoute: typeof CompareBudgetNameSecondBudgetNameIndexRoute
  CompareBudgetNameSecondBudgetNamePrijmySplatRoute: typeof CompareBudgetNameSecondBudgetNamePrijmySplatRoute
  CompareBudgetNameSecondBudgetNameVydajeSplatRoute: typeof CompareBudgetNameSecondBudgetNameVydajeSplatRoute
}

const CompareBudgetNameSecondBudgetNameRouteChildren: CompareBudgetNameSecondBudgetNameRouteChildren =
  {
    CompareBudgetNameSecondBudgetNameIndexRoute:
      CompareBudgetNameSecondBudgetNameIndexRoute,
    CompareBudgetNameSecondBudgetNamePrijmySplatRoute:
      CompareBudgetNameSecondBudgetNamePrijmySplatRoute,
    CompareBudgetNameSecondBudgetNameVydajeSplatRoute:
      CompareBudgetNameSecondBudgetNameVydajeSplatRoute,
  }

const CompareBudgetNameSecondBudgetNameRouteWithChildren =
  CompareBudgetNameSecondBudgetNameRoute._addFileChildren(
    CompareBudgetNameSecondBudgetNameRouteChildren,
  )

interface CompareRouteChildren {
  CompareIndexRoute: typeof CompareIndexRoute
  CompareBudgetNameIndexRoute: typeof CompareBudgetNameIndexRoute
  CompareBudgetNameSecondBudgetNameRoute: typeof CompareBudgetNameSecondBudgetNameRouteWithChildren
}

const CompareRouteChildren: CompareRouteChildren = {
  CompareIndexRoute: CompareIndexRoute,
  CompareBudgetNameIndexRoute: CompareBudgetNameIndexRoute,
  CompareBudgetNameSecondBudgetNameRoute:
    CompareBudgetNameSecondBudgetNameRouteWithChildren,
}

const CompareRouteWithChildren =
  CompareRoute._addFileChildren(CompareRouteChildren)

interface VladniBudgetNameRouteChildren {
  VladniBudgetNameIndexRoute: typeof VladniBudgetNameIndexRoute
  VladniBudgetNamePrijmySplatRoute: typeof VladniBudgetNamePrijmySplatRoute
  VladniBudgetNameVydajeSplatRoute: typeof VladniBudgetNameVydajeSplatRoute
}

const VladniBudgetNameRouteChildren: VladniBudgetNameRouteChildren = {
  VladniBudgetNameIndexRoute: VladniBudgetNameIndexRoute,
  VladniBudgetNamePrijmySplatRoute: VladniBudgetNamePrijmySplatRoute,
  VladniBudgetNameVydajeSplatRoute: VladniBudgetNameVydajeSplatRoute,
}

const VladniBudgetNameRouteWithChildren =
  VladniBudgetNameRoute._addFileChildren(VladniBudgetNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRouteWithChildren,
  AgregatedIndexRoute: AgregatedIndexRoute,
  MyIndexRoute: MyIndexRoute,
  PodporitIndexRoute: PodporitIndexRoute,
  PublishedIndexRoute: PublishedIndexRoute,
  VladniIndexRoute: VladniIndexRoute,
  VladniBudgetNameRoute: VladniBudgetNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
