/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/~__root'
import { Route as IndexRouteImport } from './pages/~index'
import { Route as VladniBudgetNameRouteImport } from './pages/~vladni/~$budgetName'
import { Route as VladniIndexRouteImport } from './pages/~vladni/~index'
import { Route as SupportIndexRouteImport } from './pages/~support/~index'
import { Route as PublishedIndexRouteImport } from './pages/~published/~index'
import { Route as MyIndexRouteImport } from './pages/~my/~index'
import { Route as CompareIndexRouteImport } from './pages/~compare/~index'
import { Route as AgregatedIndexRouteImport } from './pages/~agregated/~index'
import { Route as VladniBudgetNameIndexRouteImport } from './pages/~vladni/~$budgetName/~index'
import { Route as CompareBudgetNameIndexRouteImport } from './pages/~compare/~$budgetName/~index'
import { Route as VladniBudgetNameVydajeSplatRouteImport } from './pages/~vladni/~$budgetName/~vydaje.$'
import { Route as VladniBudgetNamePrijmySplatRouteImport } from './pages/~vladni/~$budgetName/~prijmy.$'
import { Route as CompareBudgetNameSecondBudgetNameIndexRouteImport } from './pages/~compare/~$budgetName/~$secondBudgetName/~index'
import { Route as CompareBudgetNameSecondBudgetNameVydajeSplatRouteImport } from './pages/~compare/~$budgetName/~$secondBudgetName/~vydaje.$'
import { Route as CompareBudgetNameSecondBudgetNamePrijmySplatRouteImport } from './pages/~compare/~$budgetName/~$secondBudgetName/~prijmy.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VladniBudgetNameRoute = VladniBudgetNameRouteImport.update({
  id: '/vladni/$budgetName',
  path: '/vladni/$budgetName',
  getParentRoute: () => rootRouteImport,
} as any)
const VladniIndexRoute = VladniIndexRouteImport.update({
  id: '/vladni/',
  path: '/vladni/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishedIndexRoute = PublishedIndexRouteImport.update({
  id: '/published/',
  path: '/published/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyIndexRoute = MyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgregatedIndexRoute = AgregatedIndexRouteImport.update({
  id: '/agregated/',
  path: '/agregated/',
  getParentRoute: () => rootRouteImport,
} as any)
const VladniBudgetNameIndexRoute = VladniBudgetNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VladniBudgetNameRoute,
} as any)
const CompareBudgetNameIndexRoute = CompareBudgetNameIndexRouteImport.update({
  id: '/compare/$budgetName/',
  path: '/compare/$budgetName/',
  getParentRoute: () => rootRouteImport,
} as any)
const VladniBudgetNameVydajeSplatRoute =
  VladniBudgetNameVydajeSplatRouteImport.update({
    id: '/vydaje/$',
    path: '/vydaje/$',
    getParentRoute: () => VladniBudgetNameRoute,
  } as any)
const VladniBudgetNamePrijmySplatRoute =
  VladniBudgetNamePrijmySplatRouteImport.update({
    id: '/prijmy/$',
    path: '/prijmy/$',
    getParentRoute: () => VladniBudgetNameRoute,
  } as any)
const CompareBudgetNameSecondBudgetNameIndexRoute =
  CompareBudgetNameSecondBudgetNameIndexRouteImport.update({
    id: '/compare/$budgetName/$secondBudgetName/',
    path: '/compare/$budgetName/$secondBudgetName/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareBudgetNameSecondBudgetNameVydajeSplatRoute =
  CompareBudgetNameSecondBudgetNameVydajeSplatRouteImport.update({
    id: '/compare/$budgetName/$secondBudgetName/vydaje/$',
    path: '/compare/$budgetName/$secondBudgetName/vydaje/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareBudgetNameSecondBudgetNamePrijmySplatRoute =
  CompareBudgetNameSecondBudgetNamePrijmySplatRouteImport.update({
    id: '/compare/$budgetName/$secondBudgetName/prijmy/$',
    path: '/compare/$budgetName/$secondBudgetName/prijmy/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agregated': typeof AgregatedIndexRoute
  '/compare': typeof CompareIndexRoute
  '/my': typeof MyIndexRoute
  '/published': typeof PublishedIndexRoute
  '/support': typeof SupportIndexRoute
  '/vladni': typeof VladniIndexRoute
  '/vladni/$budgetName': typeof VladniBudgetNameRouteWithChildren
  '/compare/$budgetName': typeof CompareBudgetNameIndexRoute
  '/vladni/$budgetName/': typeof VladniBudgetNameIndexRoute
  '/compare/$budgetName/$secondBudgetName': typeof CompareBudgetNameSecondBudgetNameIndexRoute
  '/vladni/$budgetName/prijmy/$': typeof VladniBudgetNamePrijmySplatRoute
  '/vladni/$budgetName/vydaje/$': typeof VladniBudgetNameVydajeSplatRoute
  '/compare/$budgetName/$secondBudgetName/prijmy/$': typeof CompareBudgetNameSecondBudgetNamePrijmySplatRoute
  '/compare/$budgetName/$secondBudgetName/vydaje/$': typeof CompareBudgetNameSecondBudgetNameVydajeSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agregated': typeof AgregatedIndexRoute
  '/compare': typeof CompareIndexRoute
  '/my': typeof MyIndexRoute
  '/published': typeof PublishedIndexRoute
  '/support': typeof SupportIndexRoute
  '/vladni': typeof VladniIndexRoute
  '/compare/$budgetName': typeof CompareBudgetNameIndexRoute
  '/vladni/$budgetName': typeof VladniBudgetNameIndexRoute
  '/compare/$budgetName/$secondBudgetName': typeof CompareBudgetNameSecondBudgetNameIndexRoute
  '/vladni/$budgetName/prijmy/$': typeof VladniBudgetNamePrijmySplatRoute
  '/vladni/$budgetName/vydaje/$': typeof VladniBudgetNameVydajeSplatRoute
  '/compare/$budgetName/$secondBudgetName/prijmy/$': typeof CompareBudgetNameSecondBudgetNamePrijmySplatRoute
  '/compare/$budgetName/$secondBudgetName/vydaje/$': typeof CompareBudgetNameSecondBudgetNameVydajeSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agregated/': typeof AgregatedIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/my/': typeof MyIndexRoute
  '/published/': typeof PublishedIndexRoute
  '/support/': typeof SupportIndexRoute
  '/vladni/': typeof VladniIndexRoute
  '/vladni/$budgetName': typeof VladniBudgetNameRouteWithChildren
  '/compare/$budgetName/': typeof CompareBudgetNameIndexRoute
  '/vladni/$budgetName/': typeof VladniBudgetNameIndexRoute
  '/compare/$budgetName/$secondBudgetName/': typeof CompareBudgetNameSecondBudgetNameIndexRoute
  '/vladni/$budgetName/prijmy/$': typeof VladniBudgetNamePrijmySplatRoute
  '/vladni/$budgetName/vydaje/$': typeof VladniBudgetNameVydajeSplatRoute
  '/compare/$budgetName/$secondBudgetName/prijmy/$': typeof CompareBudgetNameSecondBudgetNamePrijmySplatRoute
  '/compare/$budgetName/$secondBudgetName/vydaje/$': typeof CompareBudgetNameSecondBudgetNameVydajeSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agregated'
    | '/compare'
    | '/my'
    | '/published'
    | '/support'
    | '/vladni'
    | '/vladni/$budgetName'
    | '/compare/$budgetName'
    | '/vladni/$budgetName/'
    | '/compare/$budgetName/$secondBudgetName'
    | '/vladni/$budgetName/prijmy/$'
    | '/vladni/$budgetName/vydaje/$'
    | '/compare/$budgetName/$secondBudgetName/prijmy/$'
    | '/compare/$budgetName/$secondBudgetName/vydaje/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agregated'
    | '/compare'
    | '/my'
    | '/published'
    | '/support'
    | '/vladni'
    | '/compare/$budgetName'
    | '/vladni/$budgetName'
    | '/compare/$budgetName/$secondBudgetName'
    | '/vladni/$budgetName/prijmy/$'
    | '/vladni/$budgetName/vydaje/$'
    | '/compare/$budgetName/$secondBudgetName/prijmy/$'
    | '/compare/$budgetName/$secondBudgetName/vydaje/$'
  id:
    | '__root__'
    | '/'
    | '/agregated/'
    | '/compare/'
    | '/my/'
    | '/published/'
    | '/support/'
    | '/vladni/'
    | '/vladni/$budgetName'
    | '/compare/$budgetName/'
    | '/vladni/$budgetName/'
    | '/compare/$budgetName/$secondBudgetName/'
    | '/vladni/$budgetName/prijmy/$'
    | '/vladni/$budgetName/vydaje/$'
    | '/compare/$budgetName/$secondBudgetName/prijmy/$'
    | '/compare/$budgetName/$secondBudgetName/vydaje/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgregatedIndexRoute: typeof AgregatedIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  MyIndexRoute: typeof MyIndexRoute
  PublishedIndexRoute: typeof PublishedIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  VladniIndexRoute: typeof VladniIndexRoute
  VladniBudgetNameRoute: typeof VladniBudgetNameRouteWithChildren
  CompareBudgetNameIndexRoute: typeof CompareBudgetNameIndexRoute
  CompareBudgetNameSecondBudgetNameIndexRoute: typeof CompareBudgetNameSecondBudgetNameIndexRoute
  CompareBudgetNameSecondBudgetNamePrijmySplatRoute: typeof CompareBudgetNameSecondBudgetNamePrijmySplatRoute
  CompareBudgetNameSecondBudgetNameVydajeSplatRoute: typeof CompareBudgetNameSecondBudgetNameVydajeSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vladni/$budgetName': {
      id: '/vladni/$budgetName'
      path: '/vladni/$budgetName'
      fullPath: '/vladni/$budgetName'
      preLoaderRoute: typeof VladniBudgetNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vladni/': {
      id: '/vladni/'
      path: '/vladni'
      fullPath: '/vladni'
      preLoaderRoute: typeof VladniIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/published/': {
      id: '/published/'
      path: '/published'
      fullPath: '/published'
      preLoaderRoute: typeof PublishedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/': {
      id: '/my/'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agregated/': {
      id: '/agregated/'
      path: '/agregated'
      fullPath: '/agregated'
      preLoaderRoute: typeof AgregatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vladni/$budgetName/': {
      id: '/vladni/$budgetName/'
      path: '/'
      fullPath: '/vladni/$budgetName/'
      preLoaderRoute: typeof VladniBudgetNameIndexRouteImport
      parentRoute: typeof VladniBudgetNameRoute
    }
    '/compare/$budgetName/': {
      id: '/compare/$budgetName/'
      path: '/compare/$budgetName'
      fullPath: '/compare/$budgetName'
      preLoaderRoute: typeof CompareBudgetNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vladni/$budgetName/vydaje/$': {
      id: '/vladni/$budgetName/vydaje/$'
      path: '/vydaje/$'
      fullPath: '/vladni/$budgetName/vydaje/$'
      preLoaderRoute: typeof VladniBudgetNameVydajeSplatRouteImport
      parentRoute: typeof VladniBudgetNameRoute
    }
    '/vladni/$budgetName/prijmy/$': {
      id: '/vladni/$budgetName/prijmy/$'
      path: '/prijmy/$'
      fullPath: '/vladni/$budgetName/prijmy/$'
      preLoaderRoute: typeof VladniBudgetNamePrijmySplatRouteImport
      parentRoute: typeof VladniBudgetNameRoute
    }
    '/compare/$budgetName/$secondBudgetName/': {
      id: '/compare/$budgetName/$secondBudgetName/'
      path: '/compare/$budgetName/$secondBudgetName'
      fullPath: '/compare/$budgetName/$secondBudgetName'
      preLoaderRoute: typeof CompareBudgetNameSecondBudgetNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$budgetName/$secondBudgetName/vydaje/$': {
      id: '/compare/$budgetName/$secondBudgetName/vydaje/$'
      path: '/compare/$budgetName/$secondBudgetName/vydaje/$'
      fullPath: '/compare/$budgetName/$secondBudgetName/vydaje/$'
      preLoaderRoute: typeof CompareBudgetNameSecondBudgetNameVydajeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$budgetName/$secondBudgetName/prijmy/$': {
      id: '/compare/$budgetName/$secondBudgetName/prijmy/$'
      path: '/compare/$budgetName/$secondBudgetName/prijmy/$'
      fullPath: '/compare/$budgetName/$secondBudgetName/prijmy/$'
      preLoaderRoute: typeof CompareBudgetNameSecondBudgetNamePrijmySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VladniBudgetNameRouteChildren {
  VladniBudgetNameIndexRoute: typeof VladniBudgetNameIndexRoute
  VladniBudgetNamePrijmySplatRoute: typeof VladniBudgetNamePrijmySplatRoute
  VladniBudgetNameVydajeSplatRoute: typeof VladniBudgetNameVydajeSplatRoute
}

const VladniBudgetNameRouteChildren: VladniBudgetNameRouteChildren = {
  VladniBudgetNameIndexRoute: VladniBudgetNameIndexRoute,
  VladniBudgetNamePrijmySplatRoute: VladniBudgetNamePrijmySplatRoute,
  VladniBudgetNameVydajeSplatRoute: VladniBudgetNameVydajeSplatRoute,
}

const VladniBudgetNameRouteWithChildren =
  VladniBudgetNameRoute._addFileChildren(VladniBudgetNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgregatedIndexRoute: AgregatedIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  MyIndexRoute: MyIndexRoute,
  PublishedIndexRoute: PublishedIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  VladniIndexRoute: VladniIndexRoute,
  VladniBudgetNameRoute: VladniBudgetNameRouteWithChildren,
  CompareBudgetNameIndexRoute: CompareBudgetNameIndexRoute,
  CompareBudgetNameSecondBudgetNameIndexRoute:
    CompareBudgetNameSecondBudgetNameIndexRoute,
  CompareBudgetNameSecondBudgetNamePrijmySplatRoute:
    CompareBudgetNameSecondBudgetNamePrijmySplatRoute,
  CompareBudgetNameSecondBudgetNameVydajeSplatRoute:
    CompareBudgetNameSecondBudgetNameVydajeSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
